# Generated by Django 3.2.4 on 2021-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlsdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlbeforecut', models.URLField()),
                ('visited', models.IntegerField()),
                ('urlaftercut', models.CharField(max_length=200)),
            ],
        ),
    ]
