# Generated by Django 3.2.6 on 2021-08-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0002_rename_urlsdatabase_urlmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodels',
            old_name='urlaftercut',
            new_name='url_after_cut',
        ),
        migrations.RenameField(
            model_name='urlmodels',
            old_name='urlbeforecut',
            new_name='url_before_cut',
        ),
    ]
