# Generated by Django 3.2.6 on 2021-08-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cut', '0003_auto_20210817_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodels',
            old_name='visited',
            new_name='number_of_visitors',
        ),
    ]
